### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by blond** [enb-bem/enb-bh#31]
**Techs:**

* [x] `bh-client-module` #39
* [x] `bh-client` #39 
* [x] `bh-server-include` #38 
* [x] `bh-server` #38 
* [x] `html-from-bemjson-i18n` #37 
* [x] `html-from-bemjson` #37

**Comment by sipayRT** [comment]
Зависит от https://github.com/enb-bem/enb-bh/pull/40

**Comment by blond** [comment]
Pull Requests:
* #41
* #44
* #45
* #46
* #47
